name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Build React App
        run: |
          npm install
          npm run build

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H 98.81.199.217 >> ~/.ssh/known_hosts

      - name: Sync Frontend Files
        run: |
          rsync -avz --delete ./build/ ec2-user@98.81.199.217:/var/www/VulnScannerFrontend

      - name: Restart Nginx
        run: |
          ssh ec2-user@98.81.199.217 "sudo systemctl restart nginx"
